Repository so2zy/so2zy_FE, pull requests merged in 2023-12, with the labels that each got.

#106 Mini 71 refactor/main
  src/pages/cartReservation/CartReservation.page.tsx
  src/pages/cartReservation/components/postCartReservation.ts
  src/pages/confirm/Confirm.page.tsx
  src/pages/main/components/getPlaces.ts
  src/pages/main/components/mainAllListItem.tsx
  src/pages/main/components/mainListItem.tsx
Labels: enhancement

#108 Mini 69 refactor/place detail
  README.md
  public/_redirects
  src/components/common/Header/Header.tsx
  src/pages/cart/Cart.page.tsx
  src/pages/placeDetail/PlaceDetail.page.tsx
  src/pages/placeDetail/components/CalendarModal.tsx
Labels: feat

#113 Refactor: useCallback 사용으로 리렌더링 최소화
  src/pages/placeDetail/PlaceDetail.page.tsx
Labels: enhancement

#111 Mini 69 refactor/place detail
  src/components/SelectPeople/SelectPeople.tsx
  src/pages/placeDetail/PlaceDetail.page.tsx
  src/pages/placeDetail/components/CalendarModal.tsx
  src/pages/placeDetail/components/PeopleModal.tsx
  src/pages/reservation/Reservation.page.tsx
Labels: feat

#116 Mini 73 refactor/region search
  src/components/FilterButtons/FilterButtons.tsx
  src/components/FilterButtons/index.ts
  src/components/SortButtons/SortButtons.tsx
  src/components/SortButtons/index.ts
  src/index.tsx
  src/pages/regionList/RegionList.page.tsx
  src/pages/searchList/SearchList.page.tsx
  src/utils/formatDateRange.ts
  src/utils/shortenPrice.ts
Labels: refactor

#117 fix:accesstoken 재발급 수정
  src/components/common/Header/Header.tsx
  src/pages/signIn/components/SignIn.tsx
Labels: bug

#118 Mini 78 refactor/sign up sign in/style
  src/pages/signIn/components/SignIn.tsx
  src/pages/signUp/components/SignUp.tsx
Labels: design

#119 Mini 76 refactor/singn up sign in
  src/components/common/Header/Header.tsx
  src/pages/signIn/components/SignIn.tsx
  src/pages/signUp/components/SignUp.tsx
Labels: refactor

#120 Mini 71 refator/main
  public/index.html
  src/api/getCart.ts
  src/api/getPlaces.ts
  src/api/postCartReservation.ts
  src/components/common/ScrollToTop/ScrollToTop.tsx
  src/pages/cart/Cart.page.tsx
  src/pages/cart/components/getCart.ts
  src/pages/cartReservation/CartReservation.page.tsx
  src/pages/main/components/mainAllListItem.tsx
  src/pages/main/components/mainListItem.tsx
  src/pages/main/components/regionModal.tsx
Labels: enhancement

#121 Mini 80 feat/cart/delete/delete item
  package-lock.json
  package.json
  public/index.html
  src/__tests__/cart.test.tsx
  src/api/deleteCart.ts
  src/api/getCart.ts
  src/api/getPlaces.ts
  src/api/postCartReservation.ts
  src/components/common/ScrollToTop/ScrollToTop.tsx
  src/pages/cart/Cart.page.tsx
  src/pages/cart/components/getCart.ts
  src/pages/cartReservation/CartReservation.page.tsx
  src/pages/main/components/mainAllListItem.tsx
  src/pages/main/components/mainListItem.tsx
  src/pages/main/components/regionModal.tsx
Labels: enhancement

#123 Mini 79 feat/cart/delete
  package-lock.json
  package.json
  src/__tests__/cart.test.tsx
  src/api/deleteCart.ts
  src/pages/cart/Cart.page.tsx
  src/pages/cartReservation/CartReservation.page.tsx
Labels: enhancement

#130 Mini 80 feat/cart/delete/delete item
  src/pages/cart/Cart.page.tsx
  src/pages/cartReservation/CartReservation.page.tsx
Labels: bug
