Repository so2zy/so2zy_FE, pull requests merged in 2023-11, with the labels that each got.

#3 Mini 8 feat/place detail/design
  package-lock.json
  package.json
  src/App.tsx
  src/assets/a.ts
  src/assets/fonts/GmarketSansTTFLight.ttf
  src/components/common/Card/Card.tsx
  src/components/common/Card/index.ts
  src/components/common/Footer/Footer.tsx
  src/components/common/Footer/index.ts
  src/components/common/Header/Header.tsx
  src/components/common/Header/index.ts
  src/index.css
  src/index.tsx
  src/pages/placeDetail/components/PlaceDetail.tsx
  src/pages/placeDetail/index.ts
  src/reportWebVitals.ts
  src/styles/globalStyles.ts
  src/styles/theme.ts
Labels: design

#5 Mini 8 feat/place detail/design
  package-lock.json
  package.json
  src/App.tsx
  src/assets/a.ts
  src/assets/fonts/GmarketSansTTFLight.ttf
  src/components/common/Card/Card.tsx
  src/components/common/Card/index.ts
  src/components/common/Footer/Footer.tsx
  src/components/common/Footer/index.ts
  src/components/common/Header/Header.tsx
  src/components/common/Header/index.ts
  src/index.css
  src/index.tsx
  src/pages/placeDetail/components/PlaceDetail.tsx
  src/pages/placeDetail/index.ts
  src/reportWebVitals.ts
  src/styles/globalStyles.ts
  src/styles/theme.ts
Labels: design

#2 MINI-5-feat/header
  public/index.html
  src/App.css
  src/App.tsx
  src/assets/home.png
  src/assets/mainLogo.svg
  src/assets/shoppingBag.png
  src/components/common/Header/Header.tsx
  src/pages/cart/Cart.page.tsx
  src/pages/cart/index.ts
  src/pages/confirm/Confirm.page.tsx
  src/pages/confirm/index.ts
  src/pages/main/Main.page.tsx
  src/pages/placeDetail/PlaceDetail.page.tsx
  src/pages/regionList/RegionList.page.tsx
  src/pages/regionList/index.ts
  src/pages/reservation/Reservation.page.tsx
  src/pages/reservation/index.ts
  src/pages/searchList/SearchList.page.tsx
  src/pages/searchList/index.ts
  src/pages/signIn/SignIn.page.tsx
  src/pages/signIn/index.ts
  src/pages/signUp/SignUp.page.tsx
  src/pages/signUp/index.ts
Labels: feat

#9 Mini 11 feat/main/msw
  package-lock.json
  package.json
  public/index.html
  public/mockServiceWorker.js
  src/App.css
  src/App.tsx
  src/assets/home.png
  src/assets/mainLogo.svg
  src/assets/shoppingBag.png
  src/components/common/Header/Header.tsx
  src/index.tsx
  src/mocks/browsers.js
  src/mocks/handlers.js
  src/pages/cart/Cart.page.tsx
  src/pages/cart/index.ts
  src/pages/confirm/Confirm.page.tsx
  src/pages/confirm/index.ts
  src/pages/main/components/getPlaces.ts
  src/pages/main/components/mainAllListContainer.tsx
  src/pages/main/components/mainAllListItem.tsx
  src/pages/main/components/mainListContainer.tsx
  src/pages/main/components/mainListItem.tsx
  src/pages/main/components/regionSelectBtn.tsx
  src/pages/placeDetail/PlaceDetail.page.tsx
  src/pages/regionList/RegionList.page.tsx
  src/pages/regionList/index.ts
  src/pages/reservation/Reservation.page.tsx
  src/pages/reservation/index.ts
  src/pages/searchList/SearchList.page.tsx
  src/pages/searchList/index.ts
  src/pages/signIn/SignIn.page.tsx
  src/pages/signIn/index.ts
  src/pages/signUp/SignUp.page.tsx
  src/pages/signUp/index.ts
Labels: enhancement

#12 Mini 18 feat/main/carousel
  package-lock.json
  package.json
  src/mocks/handlers.js
  src/pages/main/components/getPlaces.ts
  src/pages/main/components/mainAllListItem.tsx
  src/pages/main/components/mainListItem.tsx
Labels: enhancement

#14 MINI-14--feat/signUp/markUp
  src/App.css
  src/App.tsx
  src/assets/mainLogoTwo.svg
  src/pages/signUp/SignUp.page.tsx
  src/pages/signUp/components/SignUp.tsx
  src/pages/signUp/index.ts
Labels: design

#13 MINI-13--feat/login/markUp
  src/App.css
  src/App.tsx
  src/assets/mainLogoTwo.svg
  src/pages/signIn/SignIn.page.tsx
  src/pages/signIn/components/SignIn.tsx
  src/pages/signIn/index.ts
Labels: design

#17 Mini 1 feat/search list
  craco.config.js
  image.png
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/App.tsx
  src/assets/images/check.svg
  src/assets/images/sort-down.svg
  src/assets/images/sort-up.svg
  src/components/Modal/Modal.tsx
  src/components/Modal/index.ts
  src/components/PriceSlider/PriceSlider.tsx
  src/components/PriceSlider/index.ts
  src/components/SelectPeople/SelectPeople.tsx
  src/components/SelectPeople/index.ts
  src/components/a.ts
  src/components/common/Footer/Footer.tsx
  src/components/common/Item/Item.tsx
  src/components/common/Item/index.ts
  src/index.tsx
  src/mocks/browser.js
  src/mocks/handlers.js
  src/pages/regionList/RegionList.page.tsx
  src/pages/regionList/index.ts
  src/pages/searchList/SearchList.page.tsx
  src/pages/searchList/index.ts
  src/recoil/a.ts
  src/recoil/searchList.ts
  tsconfig.paths.json
Labels: design, feat

#18 Mini 17 region modal
  src/mocks/handlers.js
  src/pages/main/components/getPlaces.ts
  src/pages/main/components/mainAllListItem.tsx
  src/pages/main/components/mainListItem.tsx
  src/pages/main/components/regionModal.tsx
  src/pages/main/components/regionSelectBtn.tsx
Labels: enhancement

#19 Mini 2 feat/main
  package-lock.json
  package.json
  src/App.tsx
  src/index.tsx
  src/mocks/browsers.js
  src/mocks/handlers.js
  src/pages/main/Main.page.tsx
  src/pages/main/components/getPlaces.ts
  src/pages/main/components/mainAllListContainer.tsx
  src/pages/main/components/mainAllListItem.tsx
  src/pages/main/components/mainListContainer.tsx
  src/pages/main/components/mainListItem.tsx
  src/pages/main/components/regionModal.tsx
  src/pages/main/components/regionSelectBtn.tsx
  src/styles/theme.ts
Labels: enhancement

#21 Mini 1 feat/search list
  package-lock.json
  package.json
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/index.ts
  src/components/Modal/Modal.tsx
  src/components/SelectPeople/SelectPeople.tsx
  src/mocks/handlers.js
  src/pages/searchList/SearchList.page.tsx
  src/recoil/searchList.ts
  src/styles/theme.ts
Labels: feat

#24 Mini 4 feat/place detail
  .eslintrc
  package-lock.json
  package.json
  public/index.html
  src/App.tsx
  src/index.tsx
  src/mocks/browser.js
  src/mocks/handlers.js
  src/pages/placeDetail/PlaceDetail.page.tsx
  src/pages/placeDetail/components/MapModal.tsx
  src/pages/placeDetail/components/PlaceDetail.page.tsx
  src/pages/placeDetail/components/PlaceDetail.tsx
  src/pages/placeDetail/index.ts
  src/styles/globalStyles.ts
Labels: feat

#25 Mini 32 feat/cart/mark up
  .vscode/settings.json
  src/App.tsx
  src/mocks/handlers.js
  src/pages/main/components/getPlaces.ts
  src/pages/main/components/mainAllListItem.tsx
  src/pages/main/components/mainListItem.tsx
  src/pages/placeDetail/components/PlaceDetail.page.tsx
  src/pages/reservation/Reservation.page.tsx
  src/pages/reservation/components/ReservationAgree.tsx
  src/pages/reservation/components/ReservationBtn.tsx
  src/pages/reservation/components/ReservationDesc.tsx
Labels: design

#27 Mini 36 feat/confirm/mark up
  .eslintrc
  .vscode/settings.json
  src/App.tsx
  src/components/common/Card/Card.tsx
  src/components/common/Header/Header.tsx
  src/mocks/handlers.js
  src/pages/cart/Cart.page.tsx
  src/pages/confirm/Confirm.page.tsx
  src/pages/main/components/getPlaces.ts
  src/pages/main/components/mainAllListItem.tsx
  src/pages/main/components/mainListItem.tsx
  src/pages/placeDetail/PlaceDetail.page.tsx
  src/pages/placeDetail/components/MapModal.tsx
  src/pages/placeDetail/index.ts
  src/pages/reservation/Reservation.page.tsx
  src/pages/reservation/components/ReservationAgree.tsx
  src/pages/reservation/components/ReservationBtn.tsx
  src/pages/reservation/components/ReservationDesc.tsx
  src/styles/theme.ts
Labels: design

#28 Mini 35 feat/confirm
  .eslintrc
  .vscode/settings.json
  src/App.tsx
  src/components/common/Card/Card.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Item/Item.tsx
  src/mocks/handlers.js
  src/pages/cart/Cart.page.tsx
  src/pages/confirm/Confirm.page.tsx
  src/pages/main/components/getPlaces.ts
  src/pages/main/components/mainAllListItem.tsx
  src/pages/main/components/mainListItem.tsx
  src/pages/placeDetail/PlaceDetail.page.tsx
  src/pages/placeDetail/components/MapModal.tsx
  src/pages/placeDetail/index.ts
  src/pages/reservation/Reservation.page.tsx
  src/pages/reservation/components/ReservationAgree.tsx
  src/pages/reservation/components/ReservationBtn.tsx
  src/pages/reservation/components/ReservationDesc.tsx
  src/styles/theme.ts
Labels: design

#31 Mini 12 feat/sign up
  src/App.css
  src/App.tsx
  src/assets/mainLogoTwo.svg
  src/components/common/Header/Header.tsx
  src/mocks/browser.js
  src/mocks/handler.js
  src/mocks/userList.js
  src/pages/signIn/SignIn.page.tsx
  src/pages/signIn/components/SignIn.tsx
  src/pages/signIn/index.ts
  src/pages/signUp/SignUp.page.tsx
  src/pages/signUp/components/SignUp.tsx
  src/pages/signUp/index.ts
  src/recoil/atom.ts
  src/utils/registerFunction.ts
Labels: feat

#35 Feat: 불필요한 주석 제거
  src/pages/main/components/mainAllListItem.tsx
  src/pages/main/components/mainListContainer.tsx
  src/pages/main/components/mainListItem.tsx
  src/pages/main/components/regionModal.tsx
Labels: enhancement

#34 Mini 2 feat/main
  package-lock.json
  package.json
  src/components/common/ScrollToTop/ScrollToTop.tsx
  src/components/common/ScrollToTop/index.ts
  src/mocks/handlers.js
  src/pages/main/components/getPlaces.ts
  src/pages/main/components/mainAllListItem.tsx
  src/pages/main/components/mainListContainer.tsx
  src/pages/main/components/mainListItem.tsx
  src/pages/main/components/regionModal.tsx
  src/pages/reservation/components/ReservationBtn.tsx
  src/utils/textLength.ts
  src/utils/useIntersectionObserver.ts
Labels: enhancement

#37 Mini 42 feat/token/token reissue
  craco.config.js
  package-lock.json
  package.json
  src/components/common/Header/Header.tsx
  src/jsonwebtoken-promisified.d.ts
  src/pages/signIn/components/SignIn.tsx
  src/pages/signUp/components/SignUp.tsx
  src/recoil/atom.ts
Labels: feat

#38 Mini 40 feat/token
  craco.config.js
  package-lock.json
  package.json
  src/components/common/Header/Header.tsx
  src/jsonwebtoken-promisified.d.ts
  src/pages/signIn/components/SignIn.tsx
  src/pages/signUp/components/SignUp.tsx
  src/recoil/atom.ts
Labels: feat

#43 Mini 43 feat/main/search query
  .eslintrc
  craco.config.js
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/assets/mainLogoTwo.svg
  src/components/common/Card/Card.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Item/Item.tsx
  src/jsonwebtoken-promisified.d.ts
  src/mocks/browser.js
  src/mocks/handler.js
  src/mocks/handlers.js
  src/mocks/userList.js
  src/pages/cart/Cart.page.tsx
  src/pages/confirm/Confirm.page.tsx
  src/pages/main/components/getPlaces.ts
  src/pages/main/components/mainAllListItem.tsx
  src/pages/main/components/mainListContainer.tsx
  src/pages/main/components/mainListItem.tsx
  src/pages/placeDetail/PlaceDetail.page.tsx
  src/pages/placeDetail/components/MapModal.tsx
  src/pages/placeDetail/index.ts
  src/pages/reservation/components/ReservationAgree.tsx
  src/pages/reservation/components/ReservationBtn.tsx
  src/pages/reservation/components/ReservationDesc.tsx
  src/pages/signIn/SignIn.page.tsx
  src/pages/signIn/components/SignIn.tsx
  src/pages/signIn/index.ts
  src/pages/signUp/SignUp.page.tsx
  src/pages/signUp/components/SignUp.tsx
  src/pages/signUp/index.ts
  src/recoil/atom.ts
  src/styles/theme.ts
  src/utils/registerFunction.ts
Labels: enhancement

#48 Feat: 상세페이지 props 연결 및 검색 결과 에러 해결
  src/components/common/Header/Header.tsx
  src/pages/main/components/getPlaces.ts
  src/pages/main/components/mainAllListItem.tsx
  src/pages/main/components/mainListItem.tsx
  src/utils/useFormatDate.ts
Labels: bug, enhancement, feat

#44 Mini 2 feat/main
  package-lock.json
  package.json
  src/components/common/Header/Header.tsx
  src/mocks/handlers.js
  src/pages/main/components/getPlaces.ts
  src/pages/main/components/mainAllListItem.tsx
  src/pages/main/components/mainListContainer.tsx
  src/pages/main/components/mainListItem.tsx
  src/utils/useFormatDate.ts
Labels: enhancement

#47 Mini 26 feat/region list
  .eslintrc
  package-lock.json
  package.json
  public/index.html
  src/App.tsx
  src/assets/images/map.svg
  src/components/Calendar/Calendar.tsx
  src/components/Modal/Modal.tsx
  src/components/PriceSlider/PriceSlider.tsx
  src/components/common/Header/Header.tsx
  src/mocks/browser.js
  src/mocks/handler.js
  src/mocks/handlers.js
  src/pages/regionList/RegionList.page.tsx
  src/pages/regionList/components/Map.tsx
  src/pages/regionList/components/index.ts
  src/pages/searchList/SearchList.page.tsx
  src/pages/searchList/index.ts
  src/recoil/searchList.ts
  src/utils/a.ts
  src/utils/getData.ts
  tsconfig.paths.json
Labels: feat

#50 Mini 33 feat/reservation
  .eslintrc
  package-lock.json
  package.json
  public/index.html
  src/components/common/Header/Header.tsx
  src/components/common/Loading/Loading.tsx
  src/components/common/NotFound/NotFound.tsx
  src/mocks/handlers.js
  src/pages/main/components/mainAllListItem.tsx
  src/pages/main/components/mainListItem.tsx
  src/pages/placeDetail/PlaceDetail.page.tsx
  src/pages/reservation/Reservation.page.tsx
  src/utils/useFormatDate.ts
Labels: feat

#52 Mini 51 feat/main/modal design
  .eslintrc
  package-lock.json
  package.json
  public/index.html
  src/App.tsx
  src/assets/images/map.svg
  src/components/Calendar/Calendar.tsx
  src/components/Modal/Modal.tsx
  src/components/PriceSlider/PriceSlider.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Loading/Loading.tsx
  src/components/common/NotFound/NotFound.tsx
  src/mocks/browser.js
  src/mocks/handler.js
  src/mocks/handlers.js
  src/pages/main/components/getPlaces.ts
  src/pages/main/components/mainAllListItem.tsx
  src/pages/main/components/mainListItem.tsx
  src/pages/main/components/modalData.ts
  src/pages/main/components/regionModal.tsx
  src/pages/main/components/regionSelectBtn.tsx
  src/pages/placeDetail/PlaceDetail.page.tsx
  src/pages/regionList/RegionList.page.tsx
  src/pages/regionList/components/Map.tsx
  src/pages/regionList/components/index.ts
  src/pages/reservation/Reservation.page.tsx
  src/pages/searchList/SearchList.page.tsx
  src/pages/searchList/index.ts
  src/recoil/regionModal.ts
  src/recoil/searchList.ts
  src/utils/a.ts
  src/utils/getData.ts
  src/utils/useFormatDate.ts
  tsconfig.paths.json
Labels: enhancement

#53 Mini 2 feat/main
  src/pages/main/components/getPlaces.ts
  src/pages/main/components/modalData.ts
  src/pages/main/components/regionModal.tsx
  src/pages/main/components/regionSelectBtn.tsx
  src/recoil/regionModal.ts
Labels: enhancement

#54 Feat: cursor 포인터 추가
  src/pages/main/components/regionModal.tsx
Labels: enhancement

#56 Mini 48 feat/wrap up
  src/App.tsx
  src/assets/images/chevron-down.svg
  src/components/Modal/Modal.tsx
  src/components/SelectRegion/SelectRegion.tsx
  src/components/SelectRegion/index.ts
  src/components/common/Header/Header.tsx
  src/components/common/Item/Item.tsx
  src/mocks/handlers.js
  src/pages/regionList/RegionList.page.tsx
  src/pages/searchList/SearchList.page.tsx
  src/recoil/regionList.ts
  src/recoil/searchList.ts
  src/utils/getData.ts
Labels: feat

#57 Mini 51 feat/main/modal design
  src/App.tsx
  src/assets/images/chevron-down.svg
  src/components/Modal/Modal.tsx
  src/components/SelectRegion/SelectRegion.tsx
  src/components/SelectRegion/index.ts
  src/components/common/Header/Header.tsx
  src/components/common/Item/Item.tsx
  src/mocks/handlers.js
  src/pages/main/components/regionModal.tsx
  src/pages/regionList/RegionList.page.tsx
  src/pages/searchList/SearchList.page.tsx
  src/recoil/regionList.ts
  src/recoil/searchList.ts
  src/utils/getData.ts
Labels: bug

#59 Style: 메인페이지 및 모달창 css 수정
  src/pages/main/components/mainListItem.tsx
  src/pages/main/components/regionModal.tsx
  src/pages/main/components/regionSelectBtn.tsx
Labels: enhancement

#62 Mini 40 feat/token
  public/%PUBLIC_URL%/favicon.png
  public/index.html
  src/App.tsx
  src/components/common/Header/Header.tsx
  src/pages/signIn/components/SignIn.tsx
  src/pages/signUp/components/SignUp.tsx
  src/recoil/atom.ts
Labels: feat

#66 Mini 52 feat/main/connect
  src/components/common/Header/Header.tsx
  src/pages/cart/Cart.page.tsx
  src/pages/cart/components/getCart.ts
  src/pages/main/components/getPlaces.ts
  src/pages/main/components/mainAllListContainer.tsx
  src/pages/main/components/mainAllListItem.tsx
  src/pages/main/components/mainListContainer.tsx
  src/pages/main/components/mainListItem.tsx
  src/pages/main/components/regionModal.tsx
  src/pages/reservation/Reservation.page.tsx
Labels: enhancement

#67 Mini 2 feat/main
  src/components/common/Header/Header.tsx
  src/pages/cart/Cart.page.tsx
  src/pages/cart/components/getCart.ts
  src/pages/main/components/getPlaces.ts
  src/pages/main/components/mainAllListContainer.tsx
  src/pages/main/components/mainAllListItem.tsx
  src/pages/main/components/mainListContainer.tsx
  src/pages/main/components/mainListItem.tsx
  src/pages/main/components/regionModal.tsx
  src/pages/reservation/Reservation.page.tsx
Labels: enhancement

#68 Mini 44 feat/reservation/payment
  public/favicon.png
  public/index.html
  src/App.tsx
  src/assets/images/chevron-down.svg
  src/components/Modal/Modal.tsx
  src/components/SelectRegion/SelectRegion.tsx
  src/components/SelectRegion/index.ts
  src/components/common/Header/Header.tsx
  src/components/common/Item/Item.tsx
  src/mocks/handlers.js
  src/pages/cart/Cart.page.tsx
  src/pages/cart/components/getCart.ts
  src/pages/confirm/Confirm.page.tsx
  src/pages/main/components/getPlaces.ts
  src/pages/main/components/mainAllListContainer.tsx
  src/pages/main/components/mainAllListItem.tsx
  src/pages/main/components/mainListContainer.tsx
  src/pages/main/components/mainListItem.tsx
  src/pages/main/components/modalData.ts
  src/pages/main/components/regionModal.tsx
  src/pages/main/components/regionSelectBtn.tsx
  src/pages/placeDetail/PlaceDetail.page.tsx
  src/pages/regionList/RegionList.page.tsx
  src/pages/reservation/Reservation.page.tsx
  src/pages/searchList/SearchList.page.tsx
  src/pages/signIn/components/SignIn.tsx
  src/pages/signUp/components/SignUp.tsx
  src/recoil/atom.ts
  src/recoil/regionList.ts
  src/recoil/regionModal.ts
  src/recoil/searchList.ts
  src/utils/getData.ts
  src/utils/useFormatDate.ts
Labels: feat

#72 Mini 2 feat/main
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/components/common/Header/Header.tsx
  src/index.tsx
  src/mocks/browsers.js
  src/mocks/handlers.js
  src/mocks/userList.js
  src/pages/cart/components/getCart.ts
  src/pages/main/components/mainAllListItem.tsx
Labels: bug

#74 Mini 44 feat/reservation/payment
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/components/common/Header/Header.tsx
  src/index.tsx
  src/mocks/browsers.js
  src/mocks/handlers.js
  src/mocks/userList.js
  src/pages/cart/components/getCart.ts
  src/pages/main/components/mainAllListItem.tsx
Labels: bug

#69 Mini 33 feat/reservation
  public/favicon.png
  public/index.html
  src/components/common/Header/Header.tsx
  src/mocks/handlers.js
  src/pages/confirm/Confirm.page.tsx
  src/pages/main/components/mainListItem.tsx
  src/pages/placeDetail/PlaceDetail.page.tsx
  src/pages/reservation/Reservation.page.tsx
  src/utils/useFormatDate.ts
Labels: feat

#75 Mini 40 feat/token
  package-lock.json
  package.json
  src/App.tsx
  src/assets/images/footer_github_black_icon.png
  src/assets/images/home.png
  src/assets/images/mainLogo.svg
  src/assets/images/mainLogoThree.png
  src/assets/images/mainLogoTwo.svg
  src/assets/images/shoppingBag.png
  src/components/common/Footer/Footer.tsx
  src/components/common/Header/Header.tsx
  src/pages/signIn/components/SignIn.tsx
  src/pages/signUp/components/SignUp.tsx
  src/tests/example.test.ts
Labels: feat

#77 Mini 55 feat/connect server
  public/index.html
  src/App.tsx
  src/assets/images/hotelDefaultImg.png
  src/assets/images/house.svg
  src/components/Calendar/Calendar.tsx
  src/components/SelectPeople/SelectPeople.tsx
  src/components/SelectRegion/SelectRegion.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Item/Item.tsx
  src/pages/main/components/regionModal.tsx
  src/pages/regionList/RegionList.page.tsx
  src/pages/regionList/components/Map.tsx
  src/pages/searchList/SearchList.page.tsx
  src/recoil/regionList.ts
  src/recoil/searchList.ts
  src/utils/getData.ts
Labels: design, feat

#78 Mini 61 fix/style/one
  package-lock.json
  src/components/common/Footer/Footer.tsx
  src/components/common/Header/Header.tsx
  src/pages/signIn/components/SignIn.tsx
  src/pages/signUp/components/SignUp.tsx
Labels: design

#79 Mini 60 fix/style
  package-lock.json
  src/components/common/Footer/Footer.tsx
  src/components/common/Header/Header.tsx
  src/pages/signIn/components/SignIn.tsx
  src/pages/signUp/components/SignUp.tsx
Labels: design

#82 Mini 33 feat/reservation
  src/components/common/NeedLogin/NeedLogin.tsx
  src/components/common/NeedLogin/index.tsx
  src/pages/placeDetail/PlaceDetail.page.tsx
  src/pages/reservation/Reservation.page.tsx
  src/pages/signIn/components/SignIn.tsx
Labels: feat

#83 Mini 58 feat/fix style
  src/assets/images/hotelDefaultImg2.png
  src/components/Modal/Modal.tsx
  src/components/SelectRegion/SelectRegion.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Loading/Loading.tsx
  src/components/common/NotFound/NotFound.tsx
  src/pages/main/Main.page.tsx
  src/pages/main/components/mainAllListItem.tsx
  src/pages/main/components/mainListContainer.tsx
  src/pages/main/components/mainListItem.tsx
  src/pages/main/components/regionModal.tsx
  src/pages/main/components/regionSelectBtn.tsx
  src/pages/regionList/components/Map.tsx
Labels: design

#86 Mini 45 feat/cart/get
  package-lock.json
  package.json
  public/favicon.png
  public/index.html
  public/mockServiceWorker.js
  src/App.tsx
  src/assets/images/footer_github_black_icon.png
  src/assets/images/home.png
  src/assets/images/hotelDefaultImg.png
  src/assets/images/hotelDefaultImg2.png
  src/assets/images/house.svg
  src/assets/images/mainLogo.svg
  src/assets/images/mainLogoThree.png
  src/assets/images/mainLogoTwo.svg
  src/assets/images/shoppingBag.png
  src/components/Calendar/Calendar.tsx
  src/components/Modal/Modal.tsx
  src/components/SelectPeople/SelectPeople.tsx
  src/components/SelectRegion/SelectRegion.tsx
  src/components/common/Footer/Footer.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Item/Item.tsx
  src/components/common/Loading/Loading.tsx
  src/components/common/NeedLogin/NeedLogin.tsx
  src/components/common/NeedLogin/index.tsx
  src/components/common/NotFound/NotFound.tsx
  src/index.tsx
  src/mocks/browsers.js
  src/mocks/handlers.js
  src/mocks/userList.js
  src/pages/cart/Cart.page.tsx
  src/pages/cart/components/getCart.ts
  src/pages/cartReservation/CartReservation.page.tsx
  src/pages/cartReservation/index.ts
  src/pages/confirm/Confirm.page.tsx
  src/pages/main/Main.page.tsx
  src/pages/main/components/getPlaces.ts
  src/pages/main/components/mainAllListContainer.tsx
  src/pages/main/components/mainAllListItem.tsx
  src/pages/main/components/mainListContainer.tsx
  src/pages/main/components/mainListItem.tsx
  src/pages/main/components/regionModal.tsx
  src/pages/main/components/regionSelectBtn.tsx
  src/pages/placeDetail/PlaceDetail.page.tsx
  src/pages/regionList/RegionList.page.tsx
  src/pages/regionList/components/Map.tsx
  src/pages/reservation/Reservation.page.tsx
  src/pages/searchList/SearchList.page.tsx
  src/pages/signIn/components/SignIn.tsx
  src/pages/signUp/components/SignUp.tsx
  src/recoil/atom.ts
  src/recoil/regionList.ts
  src/recoil/searchList.ts
  src/utils/getData.ts
  src/utils/useFormatDate.ts
Labels: enhancement

#96 Mini 65 hotfix/main cart
  src/components/common/ScrollToTop/ScrollToTop.tsx
  src/pages/cart/Cart.page.tsx
  src/pages/main/components/mainAllListItem.tsx
  src/pages/main/components/mainListItem.tsx
Labels: bug

#100 Design: Header 수정
  src/components/common/Header/Header.tsx
Labels: design

#101 Design: CSS 수정
  src/components/common/Header/Header.tsx
  src/pages/cart/Cart.page.tsx
  src/pages/cartReservation/CartReservation.page.tsx
  src/pages/confirm/Confirm.page.tsx
  src/pages/reservation/Reservation.page.tsx
Labels: design
